version: '3'


services:
 api_prisma_node:
   image: bitnami/postgresql
   ports:
     - 5432:5432
   environment:
     - POSTGRESQL_USERNAME=docker
     - POSTGRESQL_PASSWORD=docker
     - POSTGRESQL_DATABASE=api_express_prisma